################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# footer content
footer_content = "English"

################################### Korean language #####################################
[kr]
languageName = "Kr"
languageCode = "kr-kr"
contentDir = "content/korean"
weight = 1
# footer content
footer_content = "한국어"
